#!/usr/bin/zsh

echo "Starting full install."

svn export https://github.com/dawesry/hosted/trunk/bin ~/bin

echo "/bin and contents downloaded."

sudo chmod -R 744 ~/bin

echo "Permission Granted, scripts are now executable."

sudo echo 'export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin/sys:$PATH"
export PATH="$HOME/bin/ts:$PATH"
export PATH="$HOME/bin/clients:$PATH"' >> ~/.zshrc

echo "Added ~/bin/* sources to ~/.zshrc"

echo "Add new scripts to '~/dev/hosted/bin'."

echo "Be sure to run 'upscript' to upgrade local machines."

echo "Refreshing ZSH..."

source ~/.zshrc

exec zsh
