#!/usr/bin/bash

sudo apt install zsh git

sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

chsh -s $(which zsh)

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

echo "Set `ZSH_THEME="powerlevel10k/powerlevel10k"` in `~/.zshrc`."

wait 2

exit 0
