#!/usr/bin/zsh

svn export https://github.com/dawesry/hosted/trunk/bin ~/bin

echo "Script directory downloaded"

sudo chmod -R 744 ~/bin

echo "Permission Granted"

sudo echo 'export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin/sys:$PATH"
export PATH="$HOME/bin/ts:$PATH"
export PATH="$HOME/bin/clients:$PATH"' >> ~/.zshrc

echo "Added ~/bin/* sources to ~/.zshrc"

echo "All done, scripts are now executable!"

echo "Add new scripts to ~/bin. Be sure to run 'scriptprem' "

source ~/.zshrc

exec zsh