#!/bin/zsh

cp -r ~/bin ~/bin.old

Created `~/bin.old`.

svn export https://github.com/dawesry/hosted/trunk/bin ~/bin

echo "New /bin and contents downloaded."

sudo chmod -R 744 ~/bin

echo "Permission Granted."

echo "All done, scripts are now executable!"

echo "Add new scripts to '~/dev/hosted/bin'. Be sure to run 'gitscripts -u' to upgrade local machines."

echo "Refreshing ZSH..."

source ~/.zshrc

exec zsh
