version: '3.3'
services:
    radarr:
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=022
            - TZ=EST
        ports:
            - '7878:7878'
        volumes:
            - '/var/lib/docker/volumes/radarr_data/_data:/config'
            - '/mnt/Media/:/data/Media'
        restart: unless-stopped
        image: hotio/radarr:release
    
    sonarr:
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=022
            - TZ=USA/New_York
        ports:
            - '8989:8989'
        volumes:
            - '/var/lib/docker/volumes/sonarr_data/_data:/config'
            - '/mnt/Media/:/data/Media'
        restart: unless-stopped
        image: hotio/sonarr:release
    
    nzbget:
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=022
            - TZ=USA/New_York
        ports:
            - '6789:6789'
        volumes:
            - '/var/lib/docker/volumes/nzbget_data/_data:/config'
            - '/mnt/Media/Downloads:/Media/Downloads'
        restart: unless-stopped
        image: hotio/nzbget:release
    
    prowlarr:
        container_name: prowlarr
        ports:
            - '9696:9696'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=“USA/New_York”
        volumes:
            - '/var/lib/docker/volumes/prowlarr_data/_data:/config'
        image: hotio/prowlarr:nightly
    
    nextcloud:
        container_name: nextcloud
        ports:
            - '8080:80'
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TZ=“USA/New_York”
        volumes:
            - '/var/lib/docker/volumes/nextcloud_data/_data:/config'
            - '/mnt/Media/Cloud/Data:/data'
        image: nextcloud

networks:
  bridge:
    
